### ISSUE TITLE
config.py is missing

### ISSUE THREAD

**Issue by MeesMeijer** [PVPPBoolean/Password-Manager#1]
When i did a git -r https://github.com/PVPPBoolean/Password-Manager.git, config.py was missing in the files. Is also missing in de git reposity.

**Comment by mohammadreza-mohammadi94** [comment]
hi , 
i have same problem with config.py

**Comment by PVPPBoolean** [comment]
The config file has been added now.

You now just have to add your email id and password in the config file.
